spring:
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/assistant
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized