version: '3'

services:

  db:
    image: postgres:latest
    container_name: assistant_db
    restart: always
    environment:
      POSTGRES_DB: assistant
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local